services:
  vote:
    public: true
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 80

  result:
    public: true
    image: dockersamples/examplevotingapp_result:before
    command: node server.js
    ports:
      - 80

  worker:
    image: dockersamples/examplevotingapp_worker

  db:
    image: postgres:9.4
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379