{{- range $name, $service := .Values.services }}
{{ if $service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    stack.okteto.com/name: "{{ $.Release.Name }}"
    stack.okteto.com/service: "{{ $name }}"
    app.kubernetes.io/name: "{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    {{- include "stack.labels" $ | nindent 4 }}
  {{ if and ($service.public) ($.Values.okteto) }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{ end }}
spec:
  type: {{ if and ($service.public) (not $.Values.okteto) }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
  {{- range $port := $service.ports }}
  - port: {{ $port }}
  {{ end }}
  selector:
    stack.okteto.com/name: "{{ $.Release.Name }}"
    stack.okteto.com/service: "{{ $name }}"
---
{{- end }}
{{- end }}
