{{- range $name, $service := .Values.services }}
{{ if $service.volumes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $name }}"
  labels:
    dev.okteto.com/mola: "{{ include "mola.fullname" $ }}-{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    {{- include "mola.labels" $ | nindent 4 }}
spec:
  serviceName: "{{ $name }}"
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      dev.okteto.com/mola: "{{ include "mola.fullname" $ }}-{{ $name }}"
  template:
    metadata:
      labels:
        dev.okteto.com/mola: "{{ include "mola.fullname" $ }}-{{ $name }}"
    spec:
      containers:
        - name: "{{ $name }}"
          image: "{{ $service.image }}"
          {{ if $service.command }}
          command:
          {{ if eq (typeOf $service.command) "string" }}
            - sh
            - -c
            - {{ $service.command }}
          {{ else }}
            {{- range $command := $service.command }}
            - {{ $command }}
            {{ end }}
          {{ end }}
          {{ end }}
          {{ if $service.args }}
          args:
            {{- range $arg := $service.args }}
            - {{ $arg }}
            {{ end }}
          {{ end }}
          {{ if $service.ports }}
          ports:
            {{- range $port := $service.ports }}
            - containerPort: {{ $port }}
            {{ end }}
          {{ end }}
          {{ if $service.env }}
          env:
            {{- range $env := $service.env }}
            - name: {{ (splitn "=" 2 $env)._0 }}
              value: {{ (splitn "=" 2 $env)._1 }}
            {{ end }}
          {{ end }}
          volumeMounts:
            {{- range $index, $volume := $service.volumes }}
            - name: "volume-{{ $index }}"
              subPath: "data"
              mountPath: {{ $volume }}
            {{ end }}
  volumeClaimTemplates:
    {{- range $index, $volume := $service.volumes }}
    - metadata:
        name: "volume-{{ $index }}"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    {{ end }}
---
{{- end }}
{{- end }}
